FROM openjdk:18-slim as itBuilder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:18-slim
COPY ../../.env-it /.env
COPY --from=itBuilder dependencies/ ./
RUN true
COPY --from=itBuilder snapshot-dependencies/ ./
RUN true
COPY --from=itBuilder spring-boot-loader/ ./
RUN true
COPY --from=itBuilder application/ ./

CMD ["java", "-Dlog4j2.formatMsgNoLookups=true", "org.springframework.boot.loader.JarLauncher", "it"]
