version: "3.9"
services:
  client:
    build: react-client
    ports:
      - "3000:3000"
    depends_on:
      - rest
  rest:
    build: KotlinRest
    ports:
      - "5000:5000"
    depends_on:
      - kafka
  kafka:
    image: "bitnami/kafka:3.0.0"
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - transfer_app
  transfer_app:
    build: transfer_app
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:5.0.3"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "C:/Users/stepa/data/mongodb:/data/mongodb"
    ports:
      - "27017:27017"
    restart: unless-stopped
