version: "3.9"
services:
  client:
    build: react-client
    ports:
      - "3000:80"
    depends_on:
      - rest
  rest:
    build: KotlinRest
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - KAFKA_SERVER=kafka:9093
    depends_on:
      - kafka
  zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: "bitnami/kafka:3.0.0"
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list" ]
      interval: 2s
      timeout: 2s
      retries: 15

    depends_on:
      - zookeeper
  mongodb:
    image: "mongo:5.0.3"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "C:/Users/stepa/data/mongodb:/data/mongodb"
    ports:
      - "27017:27017"
    restart: unless-stopped

  transfer_app:
    build: transfer_app
    ports:
      - "5000:5000"
    depends_on:
      - rest
      - mongodb
      - kafka
