apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    swc.service: client
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: client
  template:
    metadata:
      labels:
        swc.service: client
    spec:
      containers:
        - image: stepanov1997/swc-react-client:latest
          name: client
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    swc.service: client
spec:
  selector:
    swc.service: client
#  type: NodePort
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
#      nodePort: 30002
      targetPort: 80
