apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    swc.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: mongo
  strategy: { }
  template:
    metadata:
      labels:
        swc.service: mongo
    spec:
      containers:
        - image: mongo:4.2.1
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    swc.service: mongo
  name: mongo
spec:
  selector:
    swc.service: mongo
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
