apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    swc.service: rest
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: rest
  strategy: { }
  template:
    metadata:
      labels:
        swc.service: rest
    spec:
      containers:
        - env:
            - name: KAFKA_SERVER
            - name: SPRING_DATA_MONGODB_URI
            - name: TRANSFERAPP_URL
          image: rest
          name: rest
          ports:
            - containerPort: 8080
            - containerPort: 5005
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rest
  labels:
    swc.service: rest
spec:
  selector:
    swc.service: rest
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "5005"
      port: 5005
      targetPort: 5005
