apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    swc.service: transfer-app
  name: transfer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: transfer-app
  strategy: { }
  template:
    metadata:
      labels:
        swc.service: transfer-app
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: "${KAFKA_INTERNAL_SERVER}"
            - name: MONGO_HOST
              value: "${MONGO_HOSTNAMES}"
            - name: MONGO_PORT
              value: "${MONGODB_PORT1}"
          image: stepanov1997/swc-transferapp:latest
          name: transfer-app
          ports:
            - containerPort: 5000
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    swc.service: transfer-app
  name: transfer-app
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    swc.service: transfer-app
