kafka:
  server: kafka:9093
spring:
  profiles:
    active: development
  kafka:
    producer:
      bootstrap-servers: ${kafka.server}
    consumer:
      bootstrap-servers: ${kafka.server}
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.server}

