kafka:
  server: localhost:9092
spring:
  profiles:
    active: development
  kafka:
    producer:
      bootstrap-servers: ${kafka.server}
    consumer:
      bootstrap-servers: ${kafka.server}
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.server}
  data:
    mongodb:
      host: 127.0.10.1
      port: 27017
