spring:
  profiles:
    active: development
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      auto-offset-reset: latest
      group-id: kotlin-rest
      enable-auto-commit: true
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
