transferapp:
  url:
kafka:
  server: localhost:9092
spring:
  profiles:
    active: development
  kafka:
    producer:
      bootstrap-servers: ${kafka.server}
    consumer:
      bootstrap-servers: ${kafka.server}
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.server}
  data:
    mongodb:
      uri: "mongodb://127.0.10.1:27017,127.0.10.2:27017,127.0.10.3:27017/test"
