transferapp:
  url: http://localhost:5000
kafka:
  server: localhost:9092
spring:
  profiles:
    active: development
  kafka:
    producer:
      bootstrap-servers: ${kafka.server}
    consumer:
      bootstrap-servers: ${kafka.server}
      auto-offset-reset: earliest
      group-id: kotlin-rest
      enable-auto-commit: false
    bootstrap-servers: ${kafka.server}
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
