apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    swc.service: mongo-rs0-2
  name: mongo-rs0-2
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: mongo-rs0-2
  strategy: {}
  template:
    metadata:
      labels:
        swc.service: mongo-rs0-2
    spec:
      containers:
        - args:
            - --replSet
            - rs0
            - --oplogSize
            - "128"
          image: mongo
          name: mongo-rs0-2
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    swc.service: mongo-rs0-2
  name: mongo-rs0-2
spec:
  selector:
    swc.service: mongo-rs0-2
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27017

