apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    swc.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      swc.service: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        swc.service: zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: bitnami/zookeeper:3.7.0
          name: zookeeper
          ports:
            - containerPort: 2181
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    swc.service: zookeeper
spec:
  selector:
    swc.service: zookeeper
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
